# Generated by Django 2.2 on 2020-12-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='course',
            field=models.ManyToManyField(related_name='playlists', to='lms_app.Course'),
        ),
    ]
