# Generated by Django 2.2 on 2021-01-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_auto_20210106_1412'),
        ('lms_app', '0003_auto_20210106_0818'),
        ('lms_app', '0003_auto_20210106_1416'),
    ]

    operations = [
    ]
